# Generated by Django 5.1.2 on 2024-11-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banner',
            field=models.ImageField(blank=True, default='banners/default.jpg', null=True, upload_to='banners/'),
        ),
    ]
