# Generated by Django 5.1.2 on 2024-11-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='banner',
            field=models.ImageField(blank=True, default='media/banners/default.jpg', null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/profile_pictures/default.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
